export const sagaActions = {
  GET_ROOMS: 'GET_ROOMS',
  CONNECT: 'CONNECT',
  DISCONNECT: 'DISCONNECT',
  SEND: 'SEND',
};

export const MESSAGES = {
  CONNECTED: 'CONNECTED',
  DISCONNECTED: 'DISCONNECTED',
  USER_CONNECTED: 'USER_CONNECTED',
  USER_DISCONNECTED: 'USER_DISCONNECTED',
  SEND: 'SEND',
};
